import earsip from '../assets/earsip-kai.jpg'
import kai2 from '../assets/kai2.png'
import kai3 from '../assets/kai3.png'
import kai4 from '../assets/kai4.png'
import kai5 from '../assets/kai5.png'
import raso from '../assets/raso-wong-kito.jpg'
import raso2 from '../assets/raso2.png'
import raso3 from '../assets/raso3.png'
import raso4 from '../assets/raso4.png'
import { useRef } from 'react'

const projects = [
  { number: 'PROJECT 01', type: 'Enterprise System Architecture', title: 'E-ARSIP KAI — DIGITAL ARCHIVE MANAGEMENT', description: 'Built a centralized digital archive platform for Kereta Api Indonesia (KAI), with RBAC, document management, advanced search, reporting, notifications, and lifecycle monitoring to streamline archive operations across user roles.', stack: ['PHP 8.2', 'MYSQL', 'JAVASCRIPT', 'FPDF ENGINE', 'RBAC SECURITY'], action: 'EXPLORE SPECIFICATION', images: [earsip, kai2, kai3, kai4, kai5] },
  { number: 'PROJECT 02', type: 'Culinary Archive', title: 'RASO WONG KITO — PALEMBANG CULINARY HERITAGE', description: "Developed a responsive web platform dedicated to exploring Palembang’s culinary heritage. The project combines modern web design, intuitive navigation, and structured culinary content to create an engaging digital experience for discovering traditional Palembang food and culture.", stack: ['SEMANTIC HTML5', 'MODERN CSS', 'VANILLA ES6+', 'TECHNICAL SEO', 'SCHEMA.ORG'], action: 'INSPECT ARCHITECTURE', href: 'https://rasowongkito.vercel.app/', images: [raso, raso2, raso3, raso4] },
]

function SectionHeading({ catalog, title, detail }) { return <div className="section-heading"><div><p className="catalog">{catalog}</p><h2>{title}</h2></div>{detail && <p className="heading-detail">{detail}</p>}</div> }
function ProjectSlider({ project }) { const slider = useRef(null); const move = (direction) => slider.current.scrollBy({ left: direction * slider.current.clientWidth, behavior: 'smooth' }); return <div className="project-image"><div className="project-slider" ref={slider}>{project.images.map((image, index) => <img key={index} src={image} alt={`${project.title} ${index + 1}`} />)}</div><div className="slider-controls"><button type="button" onClick={() => move(-1)} aria-label="Foto sebelumnya">←</button><span>GESER FOTO</span><button type="button" onClick={() => move(1)} aria-label="Foto berikutnya">→</button></div></div> }
export function Projects() { return <section className="works section" id="work"><div className="shell"><SectionHeading title="SELECTED PROJECT" /><div className="project-list">{projects.map((project, index) => <article className={`project ${index === 1 ? 'reverse' : ''}`} key={project.number}><div className="project-info"><div><span className="project-number">{project.number}</span><em>{project.type}</em></div><h3>{project.title}</h3><p>{project.description}</p><div className="stack"><label>TECHNICAL STACK</label><div>{project.stack.map((item) => <span key={item}>{item}</span>)}</div></div><a className="project-link" href={project.href || '#contact'}>{project.action} <b>→</b></a></div><ProjectSlider project={project} /></article>)}</div></div></section> }
export function About() { const principles = [['01 // WEB ENGINEERING', 'Clean & Scalable', 'Building responsive web applications with clean architecture, maintainable code, and a strong focus on performance, usability, and long-term scalability.'], ['02 // SEARCH OPTIMIZATION', 'Discoverable by Design', 'Applying SEO fundamentals such as semantic HTML, structured content, metadata, responsive design, and performance optimization to create websites that are easier to discover and navigate.'], ['03 // CYBER SECURITY', 'Security-Minded Development', 'Developing with security in mind through input validation, secure authentication practices, access control, safe data handling, and awareness of common web application vulnerabilities.']]; return <section className="about section" id="about"><div className="shell"><SectionHeading title="PRINCIPLES & BELIEFS" /><blockquote>“I build <em>modern web experiences</em>, practical digital systems, <em>search-friendly</em> platforms, and <em>security-conscious</em> applications.”</blockquote><div className="principles">{principles.map(([number, title, description]) => <article key={number}><p>{number}</p><h3>{title}</h3><span>{description}</span></article>)}</div></div></section> }
export function Skills() { const rows = [['Web Development', 'Modern JavaScript (ES6+), PHP 8.x, Tailwind CSS, Semantic HTML5, MySQL, REST APIs', 'Production Grade'], ['Technical SEO', 'Core Web Vitals Optimization, Schema.org Markup, XML Sitemaps, Crawl Budget Strategy', 'Advanced Strategy'], ['Cyber Security', 'Vulnerability Assessment, OWASP Top 10 Hardening, RBAC, Data Sanitization, Audit Logging', 'Enterprise Defensive'], ['Tools & Infrastructure', 'Git, GitHub, Apache/Nginx, Linux Server Administration, Postman, Chrome DevTools', 'Daily Workflow']]; return <section className="skills section" id="skills"><div className="shell"><SectionHeading title="TECHNICAL DOMAINS" /><div className="table-wrap"><table><thead><tr><th>DISCIPLINE</th><th>PRIMARY STACK & METHODOLOGY</th><th>COMPETENCE LEVEL</th></tr></thead><tbody>{rows.map((row) => <tr key={row[0]}>{row.map((cell, index) => <td key={cell} className={index === 0 ? 'discipline' : ''}>{cell}</td>)}</tr>)}</tbody></table></div></div></section> }
