import earsip from '../assets/earsip-kai.jpg'
import raso from '../assets/raso-wong-kito.jpg'

const projects = [
  { number: 'PROJECT 01', type: 'Enterprise System Architecture', title: 'E-ARSIP KAI — DIGITAL ARCHIVE MANAGEMENT', description: 'Engineered a high-throughput, secure institutional document management platform for Kereta Api Indonesia (KAI). Implements granular Role-Based Access Control (RBAC), end-to-end document encryption, audit trails, and automated indexing for tens of thousands of classified records.', stack: ['PHP 8.2', 'MYSQL', 'JAVASCRIPT', 'FPDF ENGINE', 'RBAC SECURITY'], action: 'EXPLORE SPECIFICATION', image: earsip },
  { number: 'PROJECT 02', type: 'Digital Gastronomy & Archive', title: 'RASO WONG KITO — HERITAGE & GASTRONOMY', description: "An editorial culinary archive celebrating South Sumatra's authentic gastronomic culture. Architected with strict semantic HTML5, zero-bloat vanilla scripts, structured JSON-LD schema ontologies for recipe rich snippets, and sub-second Core Web Vitals performance.", stack: ['SEMANTIC HTML5', 'MODERN CSS', 'VANILLA ES6+', 'TECHNICAL SEO', 'SCHEMA.ORG'], action: 'INSPECT ARCHITECTURE', image: raso },
]

function SectionHeading({ catalog, title, detail }) { return <div className="section-heading"><div><p className="catalog">{catalog}</p><h2>{title}</h2></div>{detail && <p className="heading-detail">{detail}</p>}</div> }
export function Projects() { return <section className="works section" id="work"><div className="shell"><SectionHeading title="SELECTED PROJECT" /><div className="project-list">{projects.map((project, index) => <article className={`project ${index === 1 ? 'reverse' : ''}`} key={project.number}><div className="project-info"><div><span className="project-number">{project.number}</span><em>{project.type}</em></div><h3>{project.title}</h3><p>{project.description}</p><div className="stack"><label>TECHNICAL STACK</label><div>{project.stack.map((item) => <span key={item}>{item}</span>)}</div></div><a className="project-link" href="#contact">{project.action} <b>→</b></a></div><div className="project-image"><img src={project.image} alt={`${project.title} interface`} /></div></article>)}</div></div></section> }
export function About() { const principles = [['01 // WEB ENGINEERING', 'Deterministic & Resilient', 'Crafting responsive applications with minimal dependencies, exceptional performance metrics, and clean code that scales cleanly across enterprise lifecycles.'], ['02 // SEARCH OPTIMIZATION', 'Semantic Indexing', 'Deep technical SEO implementation from server headers, JSON-LD schemas, to hyper-optimized Core Web Vitals guarantees organic discoverability without artificial tricks.'], ['03 // CYBER SECURITY', 'Defensive Architecture', 'Protecting integrity through strict input sanitization, OWASP mitigation, cryptographic hashing, and hardened access policies from the database to presentation layer.']]; return <section className="about section" id="about"><div className="shell"><SectionHeading title="PRINCIPLES & BELIEFS" /><blockquote>“I build <em>modern web experiences</em>, digital systems, <em>SEO-friendly</em> platforms, and <em>defensible secure</em> applications.”</blockquote><div className="principles">{principles.map(([number, title, description]) => <article key={number}><p>{number}</p><h3>{title}</h3><span>{description}</span></article>)}</div></div></section> }
export function Skills() { const rows = [['Web Development', 'Modern JavaScript (ES6+), PHP 8.x, Tailwind CSS, Semantic HTML5, MySQL, REST APIs', 'Production Grade'], ['Technical SEO', 'Core Web Vitals Optimization, Schema.org Markup, XML Sitemaps, Crawl Budget Strategy', 'Advanced Strategy'], ['Cyber Security', 'Vulnerability Assessment, OWASP Top 10 Hardening, RBAC, Data Sanitization, Audit Logging', 'Enterprise Defensive'], ['Tools & Infrastructure', 'Git, GitHub, Apache/Nginx, Linux Server Administration, Postman, Chrome DevTools', 'Daily Workflow']]; return <section className="skills section" id="skills"><div className="shell"><SectionHeading title="TECHNICAL DOMAINS" /><div className="table-wrap"><table><thead><tr><th>DISCIPLINE</th><th>PRIMARY STACK & METHODOLOGY</th><th>COMPETENCE LEVEL</th></tr></thead><tbody>{rows.map((row) => <tr key={row[0]}>{row.map((cell, index) => <td key={cell} className={index === 0 ? 'discipline' : ''}>{cell}</td>)}</tr>)}</tbody></table></div></div></section> }
